actors:
  little_hand_s:
    image_url: /images/actors/little_hand_s.png
    name: little_hand_s
    url: https://twitter.com/little_hand_s
  j5ik2o:
    image_url: /images/actors/j5ik2o.png
    name: j5ik2o
    url: https://twitter.com/j5ik2o
  MinoDriven:
    image_url: /images/actors/MinoDriven.png
    name: MinoDriven
    url: https://twitter.com/MinoDriven
  a_suenami:
    image_url: /images/actors/a_suenami.png
    name: a_suenami
    url: https://twitter.com/a_suenami
  
author: alice
description: Example description
description_long: Example long description
email: dddcj.radio@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: dddcj
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: DDD Radio
url: http://example.com
